@startuml
 actor navegador
 entity delete
 boundary "confirmDeleteCom" as Fun
 boundary "company.routes.js" as Rou
 control "company.controller.js" as Co
 entity "company.model" as Mo
 database sql
 activate navegador
 navegador->delete
 deactivate navegador
 activate delete
 delete->Fun
 deactivate delete
 activate Fun
 Fun->>Rou:DELETE(/nuclea/company/delete/idDiaFeriado)
 activate Rou
 Rou->Co:Delete(req,res)
 deactivate Rou
 activate Co
 Co->>Mo:Delete(req.params.idEmpresa)
 activate Mo
 Mo->>sql:execute('DELETE FROM Empresa WHERE idEmpresa=?',[id])
 activate sql
 sql-->>Mo:Query OK
 deactivate sql
 Mo-->>Co:Promesa
 deactivate Mo
 
 Co-->>Fun:return res.JSON
 deactivate Co
 Fun->>Fun:Data res.JSON()
 
 Fun->navegador:HTML
 deactivate Fun
 activate navegador
 deactivate navegador
 
 
 @enduml
